<template>
<b-container class="p-1">
  <template v-if="mode === 'edit'">
    <b-row align-v="center">
      <h4 style="color: var(--primary);">工番の編集</h4>
    </b-row>
  </template>
  <b-row align-v="center">
    <b-col class="text-right p-0" cols="3">
      工番
    </b-col>
    <b-col cols="4" class="pr-0">
      <b-input type="number" :disabled="mode === 'edit' || controls.isIdAutoGenerated" v-model="form.project.projectId"></b-input>
    </b-col>
    <b-col cols="5">
      <b-checkbox v-model="controls.isIdAutoGenerated">自動採番</b-checkbox>
    </b-col>
  </b-row>
  <b-row align-v="center">
    <b-col class="text-right p-0" cols="3">
      工事名
    </b-col>
    <b-col>
      <b-input v-model="form.project.projectTitle"></b-input>
    </b-col>
  </b-row>
  <b-row align-v="center">
    <b-col class="text-right p-0" cols="3">
      ステータス
    </b-col>
    <b-col>
      <b-select :options="$tstore.bundles.options.projectStatus" v-model="form.project.status"></b-select>
    </b-col>
  </b-row>
  <b-row align-v="center">
    <b-col class="text-right">
      <b-button :disabled="$v.form.project?.$invalid" @click="register">{{ mode === "edit" ? "更新" : "作成" }}</b-button>
    </b-col>
  </b-row>
</b-container>
</template>

<style scoped>
.container {
  & > .row {
    margin-bottom: 20px;
  }
  & > :last-child {
    margin-bottom: 0px;
  }
}
</style>

<script lang="ts">
import { Project, projectValidator } from '@/schema/Project'

export default {
  mounted() {
    if(this.value != null) {
      const formKeys = Object.getOwnPropertyNames(this.form.project)
      Object.entries(this.value).forEach(([k,v]) => {
        if(formKeys.some(fk => fk === k)) {
          this.form.project[k] = v
        }
      })
    } else {
      this.controls.isIdAutoGenerated = true
      this.setNextProjectId()
    }
  },
  props: {
    mode: {
      type: String,
      default: "new",
    },
    value: {
      type: Project,
      required: false,
    },
  },
  data() {
    return {
      controls: {
        isIdAutoGenerated: false,
      },
      form: {
        project: new Project() as Project & {[key: string]: any},
      }
    }
  },
  watch: {
    "controls.isIdAutoGenerated": function() {
      if( ! this.controls.isIdAutoGenerated) {
        return
      }
      this.setNextProjectId()
    }
  },
  validations() {
    return {
      form: {
        project: projectValidator(this.form.project)
      }
    }
  },
  methods: {
    async setNextProjectId() {
      this.form.project.projectId = await this.$firebase.db.fetchNextProjectId()
      console.log(`this.form.project.projectId: ${this.form.project.projectId}`)
    },
    async register() {
      // <b-input type="number" /> somehow turns the value into string, so below code will turn it to number
      this.form.project.projectId = parseInt(this.form.project.projectId.toString())

      const allProjects = await this.$firebase.db.fetchProjectsWithStatusFilter()
      if(this.mode !== "edit" && allProjects.some(project => project.projectId === this.form.project.projectId)) {
        this.$bvModal.msgBoxOk(this.newLiner(`エラー：該当の工番「${this.form.project.projectId}」は既に使用されています。\n他の工番を割り当ててください。`))
        return
      }

      if(this.mode === "edit") {
        if(this.value?.projectId !== this.form.project.projectId) {
          if( ! await this.$bvModal.msgBoxConfirm(this.newLiner("工事番号の変更を行っても、既に入力された日報などの工事番号は元の番号のままで変更されません。\n\nそれでも変更を行いますか？"))) {
            return;
          }
        }

        await this.$firebase.db.updateProject(this.form.project.docId, this.form.project.toJSON())
        .then(() => {
          this.$emit("input", this.form)
          this.$bvModal.msgBoxOk("工番情報の更新が完了しました")
        }).catch(error => {
          this.$bvModal.msgBoxOk(this.newLiner(`警告：工番情報の更新に失敗しました。\n${JSON.stringify(error)}`))
        })

      } else {
        await this.$firebase.db.registerNewProject(this.form.project.toJSON())
        .then(async () => {
          this.$emit("input", this.form)
          this.$bvModal.msgBoxOk("工番の新規登録が完了しました")
        }).catch(error => {
          this.$bvModal.msgBoxOk(`警告：エラーが発生しました：${JSON.stringify(error)}`)
        })
      }

      if(this.mode !== 'edit') {
        this.setNextProjectId()
      }
    },
  }
}
</script>